#!/bin/python3
#Omer Mirghani
#3/19/2020
import math
import os
import random
import re
import sys

# Complete the beautifulDays function below.
def beautifulDays(i, j, k):
    count=0
    for f in range(i,j+1):
        v=0
        Reverse = 0
        j=f    
        while(f > 0):    
         Reminder = f %10    
         Reverse = (Reverse *10) + Reminder    
         f = f //10
        if((j-Reverse)%k==0):
          print(j,Reverse)
          count+=1  
    return(count)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    ijk = input().split()

    i = int(ijk[0])

    j = int(ijk[1])

    k = int(ijk[2])

    result = beautifulDays(i, j, k)

    fptr.write(str(result) + '\n')

    fptr.close()
