#!/bin/python3
#by Omer Mirghani

import math
import os
import random
import re
import sys

# Complete the circularArrayRotation function below.
def circularArrayRotation(a, k, queries):
    print(a)
    x=[]
    l = len(a)
    for i in range(k):
        a.insert(0,a[-1])
        a.pop(l)
    
    for i in (queries):
        x.append(a[i])
    return(x)
   
    #print(k)
    #print(queries)
    
    print(a)

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nkq = input().split()

    n = int(nkq[0])

    k = int(nkq[1])

    q = int(nkq[2])

    a = list(map(int, input().rstrip().split()))

    queries = []

    for _ in range(q):
        queries_item = int(input())
        queries.append(queries_item)

    result = circularArrayRotation(a, k, queries)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
