#!/bin/python3
#by Omer Mirghani
#3/19/2020
import math
import os
import random
import re
import sys

# Complete the designerPdfViewer function below.
def designerPdfViewer(h, word):
    print(h)
    print(word)
    intword=[]
    l=len(word)
    for i in range(l):
       intword.append(h[ord(word[i])-97])
    return(max(intword)*l)
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    h = list(map(int, input().rstrip().split()))

    word = input()

    result = designerPdfViewer(h, word)

    fptr.write(str(result) + '\n')

    fptr.close()
