#!/bin/python3
#By Omer  Mirghani
#22/3/2020
import math
import os
import random
import re
import sys

# Complete the libraryFine function below.
def libraryFine(d1, m1, y1, d2, m2, y2):
    count=0
    dfine=15
    mfine=500
    yearfine=10000
    if(y1>y2):
        count+=yearfine*(y1-y2)
    elif(y1==y2):
        if(m1>m2):
            count+=mfine*(m1-m2)
        elif(m1==m2):
            if(d1>d2):
             count+=dfine*(d1-d2)
            else:
             count=0
        else:
            count=0
    else:
        count=0
    return(count)


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    d1M1Y1 = input().split()

    d1 = int(d1M1Y1[0])

    m1 = int(d1M1Y1[1])

    y1 = int(d1M1Y1[2])

    d2M2Y2 = input().split()

    d2 = int(d2M2Y2[0])

    m2 = int(d2M2Y2[1])

    y2 = int(d2M2Y2[2])

    result = libraryFine(d1, m1, y1, d2, m2, y2)

    fptr.write(str(result) + '\n')

    fptr.close()
