#!/bin/python3
#By Omer Mirghani
import math
import os
import random
import re
import sys

# Complete the permutationEquation function below.
def permutationEquation(p):
    l = len(p)
    x=[]
    for i in range(0,len(p)):
        x.append(p.index(p.index(i+1)+1)+1)
    return(x)
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    p = list(map(int, input().rstrip().split()))

    result = permutationEquation(p)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
