#!/bin/python3
#Omer Mirghani
#3/19/2020

import math
import os
import random
import re
import sys

# Complete the utopianTree function below.
def utopianTree(n):
   p=0
   h=1
   c=0
   
   while(p<n):
     print(p,h,'\n')
     if p%2==0:
        h*=2
     else:
        h+=1
   
    
     p+=1
   return(h)

    



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input())

    for t_itr in range(t):
        n = int(input())

        result = utopianTree(n)

        fptr.write(str(result) + '\n')

    fptr.close()
